# Copyright (c) 2007-2008 Michael Specht
# 
# This file is part of GPF.
# 
# GPF is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# GPF is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with GPF.  If not, see <http://www.gnu.org/licenses/>.

# save as gpf_constants.rb

$gs_GpfServer = 'http://gpf.uni-muenster.de:19810'
$gi_BrowseWidth = 120

$gk_TripletToAminoAcid = {
	'AAA' => 'K',
	'AAC' => 'N',
	'AAG' => 'K',
	'AAT' => 'N',
	'AA.' => 'X',
	'ACA' => 'T',
	'ACC' => 'T',
	'ACG' => 'T',
	'ACT' => 'T',
	'AC.' => 'T',
	'AGA' => 'R',
	'AGC' => 'S',
	'AGG' => 'R',
	'AGT' => 'S',
	'AG.' => 'X',
	'ATA' => 'I',
	'ATC' => 'I',
	'ATG' => 'M',
	'ATT' => 'I',
	'AT.' => 'X',
	'A.A' => 'X',
	'A.C' => 'X',
	'A.G' => 'X',
	'A.T' => 'X',
	'A..' => 'X',
	'CAA' => 'Q',
	'CAC' => 'H',
	'CAG' => 'Q',
	'CAT' => 'H',
	'CA.' => 'X',
	'CCA' => 'P',
	'CCC' => 'P',
	'CCG' => 'P',
	'CCT' => 'P',
	'CC.' => 'P',
	'CGA' => 'R',
	'CGC' => 'R',
	'CGG' => 'R',
	'CGT' => 'R',
	'CG.' => 'R',
	'CTA' => 'L',
	'CTC' => 'L',
	'CTG' => 'L',
	'CTT' => 'L',
	'CT.' => 'L',
	'C.A' => 'X',
	'C.C' => 'X',
	'C.G' => 'X',
	'C.T' => 'X',
	'C..' => 'X',
	'GAA' => 'E',
	'GAC' => 'D',
	'GAG' => 'E',
	'GAT' => 'D',
	'GA.' => 'X',
	'GCA' => 'A',
	'GCC' => 'A',
	'GCG' => 'A',
	'GCT' => 'A',
	'GC.' => 'A',
	'GGA' => 'G',
	'GGC' => 'G',
	'GGG' => 'G',
	'GGT' => 'G',
	'GG.' => 'G',
	'GTA' => 'V',
	'GTC' => 'V',
	'GTG' => 'V',
	'GTT' => 'V',
	'GT.' => 'V',
	'G.A' => 'X',
	'G.C' => 'X',
	'G.G' => 'X',
	'G.T' => 'X',
	'G..' => 'X',
	'TAA' => '$',
	'TAC' => 'Y',
	'TAG' => '$',
	'TAT' => 'Y',
	'TA.' => 'X',
	'TCA' => 'S',
	'TCC' => 'S',
	'TCG' => 'S',
	'TCT' => 'S',
	'TC.' => 'S',
	'TGA' => '$',
	'TGC' => 'C',
	'TGG' => 'W',
	'TGT' => 'C',
	'TG.' => 'X',
	'TTA' => 'L',
	'TTC' => 'F',
	'TTG' => 'L',
	'TTT' => 'F',
	'TT.' => 'X',
	'T.A' => 'X',
	'T.C' => 'X',
	'T.G' => 'X',
	'T.T' => 'X',
	'T..' => 'X',
	'.AA' => 'X',
	'.AC' => 'X',
	'.AG' => 'X',
	'.AT' => 'X',
	'.A.' => 'X',
	'.CA' => 'X',
	'.CC' => 'X',
	'.CG' => 'X',
	'.CT' => 'X',
	'.C.' => 'X',
	'.GA' => 'X',
	'.GC' => 'X',
	'.GG' => 'X',
	'.GT' => 'X',
	'.G.' => 'X',
	'.TA' => 'X',
	'.TC' => 'X',
	'.TG' => 'X',
	'.TT' => 'X',
	'.T.' => 'X',
	'..A' => 'X',
	'..C' => 'X',
	'..G' => 'X',
	'..T' => 'X',
	'...' => 'X'
}
